name: Deploy Windows Server 2022 Entra ID Environment

on:
  workflow_dispatch:  # Manual triggering only for security
    inputs:
      deploymentName:
        description: 'Deployment name (for tracking)'
        required: true
        default: 'thorlabs-windows-server-deployment'
      resourceGroupName:
        description: 'Resource group name'
        required: true
        default: 'thorlabs-rg'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ADMIN_PASSWORD: ${{ secrets.WINDOWS_ADMIN_PASSWORD }}  # Separate secret for Windows VMs
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure Subscription
        run: |
          az account set --subscription "$AZURE_SUBSCRIPTION_ID"

      - name: Validate Bicep Template
        run: |
          az deployment group validate \
            --resource-group ${{ github.event.inputs.resourceGroupName }} \
            --template-file bicep/windows-server-entra-id.bicep \
            --parameters adminPassword="$ADMIN_PASSWORD" \
            --parameters @bicep/windows-server-entra-id.parameters.json

      - name: Deploy Windows Server Bicep Template
        run: |
          az deployment group create \
            --name "${{ github.event.inputs.deploymentName }}" \
            --resource-group ${{ github.event.inputs.resourceGroupName }} \
            --template-file bicep/windows-server-entra-id.bicep \
            --parameters adminPassword="$ADMIN_PASSWORD" \
            --parameters @bicep/windows-server-entra-id.parameters.json \
            --verbose

      - name: Output Deployment Information
        run: |
          echo "Deployment completed. Check the Azure portal for VM details."
          echo "Remember to run the PowerShell setup scripts on the VM:"
          echo "1. scripts/windows-server-entra-prereqs.ps1"
          echo "2. scripts/windows-server-mdi-prereqs.ps1"